title:  Douglas Whalin
tagline:  late antique and medieval historian
author:
  name: Douglas Whalin
  
#google-ID: 'UA-80213386-1'

menu:
- {name: 'Research', url: 'about.html'}
- {name: 'Blog', url: 'writing.html'}
- {name: 'CV', url: 'cv.html'}
- {name: 'Contact', url: 'contact.html'}

social:
- {icon: 'github', link: 'https://www.github.com/douglaswhalin'}
- {icon: 'academia.edu', link: 'https://cambridge.academia.edu/DouglasWhalin'}



# Available social icons are powered by Font Awesome, so you can use any icon that they offer
