title:  Douglas Whalin
tagline:  late antique historian
author:
  name: Douglas Whalin
  
#google-ID: 'UA-80213386-1'

menu:
- {name: 'Research', url: 'about.html'}
- {name: 'Publications', url: 'papers.html'}
- {name: 'CV', url: 'cv.html'}

social:
- {icon: 'github', link: 'https://www.github.com/douglaswhalin'}
- {icon: 'graduation-cap', link: 'https://cambridge.academia.edu/DouglasWhalin'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Share this post:'

related_posts: 'Other posts you might like:'

#post_date_prefix: 'Written on'

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
